// FILM.TIMELINE: the shot list and audio cue list for "Hayk: The Burger Quest".
// Owner: storyboard. Visual rules: docs/art-bible.md. Characters: src/cast.js. Effects and props: src/props.js.
// 120 bpm: a beat is 0.5 s (12 frames at 24 fps), a bar is 2 s. Every shot boundary sits on the beat grid.
// All on-screen text is English. Anime look: cel-shaded characters, speed lines, impact frames.
(function () {
  'use strict';
  const FILM = window.FILM;

  const S = (id, file, start, end, title, brief, extra) =>
    Object.assign({ id, file, start, end, mode: 'illustrated', post: false, title, transitionIn: { kind: 'cut', dur: 0 }, brief }, extra || {});

  FILM.TIMELINE = {
    title: 'Hayk: The Burger Quest',
    bpm: 120,
    duration: 120,
    fps: 24,
    width: 1080,
    height: 1920,
    shots: [
      // ACT 1: YEREVAN (0-26)
      S('cold-open', '01-cold-open.js', 0, 4, 'Title: HAYK: THE BURGER QUEST',
        'Anime opening title card. Deep indigo night sky over Yerevan with Mount Ararat (two peaks, snow caps, FILM.fx.ararat) on the horizon, a few city lights. Radial focus lines explode from centre on beat 0.5 s with an impact flash. The title slams in on the beat 1.0 s in three drawings with overshoot: "HAYK" huge (size ~190, gold fill, thick black outline, dark red drop shadow) and under it "THE BURGER QUEST" (size ~70, white). A spinning burger (FILM.fx.burger) with sparkles pops in above the title at 2.0 s. Small caption at 3.0 s: "EPISODE 1" in a black tag. Katakana accent "バーガー" faint behind the title. Frame 0 shows the sky, mountain and first focus lines already drawn.'),
      S('trader-den', '02-trader-den.js', 4, 9, 'Hayk, trader, founder of LiquidityScan',
        'Night, Hayk\'s room in Yerevan. Hayk (FILM.cast.hayk, pose "sit", face "focused") sits in a gaming chair at a desk with three glowing monitors showing green and red candlestick charts (FILM.fx.candles) and the LiquidityScan logo (FILM.fx.lsLogo) with the word "LIQUIDITYSCAN" on the middle monitor. Monitor glow (cyan/green) rims his face. Camera slowly pushes in. At 1.0 s a character intro card slides in from the left in classic anime style: black slanted bar with "HAYK" (size 110) and under it "TRADER / FOUNDER OF LIQUIDITYSCAN" (size 40). At 3.0 s a green candle spikes up, his eyes glint (sparkle on the eye anchor) and a small SFX "PING!" pops. Window behind shows Yerevan night and Ararat silhouette. Coffee mug steaming on the desk.'),
      S('big-decision', '03-big-decision.js', 9, 13, 'I am going to Spain',
        'Same room, dramatic. On 9.0 (t=0) Hayk stands up so fast the chair spins away (motion smear). Low-angle hero shot: Hayk pose "fist", face "determined", wind blowing his hoodie, red-orange focus lines and a burning aura (FILM.fx.aura) behind him, background turns to a flat dramatic gradient. Shout bubble (spiky, FILM.fx.bubble shout:true) at 0.5 s: "I\'M GOING TO SPAIN!" then a second smaller bubble at 2.0 s: "...TO FIND INVESTORS!". Screen shake on 9.5 and 11.0 (FILM.fx.shake). A tiny world map in the corner with a dotted line Armenia -> Spain. Sparkle glints on his eyes.'),
      S('goofy-knows', '04-goofy-knows.js', 13, 17, 'Goofy sees the suitcase',
        'Apartment hallway, daytime. A packed suitcase (FILM.fx.suitcase) with an airplane tag stands by the door. Goofy (FILM.cast.goofy, pose "sit") looks at it; at 1.0 s his face switches to "sad" with huge wobbling anime tear-filled eyes, ears droop. Camera push-in on Goofy with soft pink sparkle background and light blue vertical gloom lines (anime depression lines) above his head at 2.0 s. Small thought bubble at 2.0 s: "...you\'re leaving me?". Hayk\'s legs only (cropped, FILM.cast.hayk at large scale, feet visible) step into frame at the right edge at 3.0 s with a sweat drop on screen.'),
      S('leash-handoff', '05-leash-handoff.js', 17, 21, 'Grant takes the leash',
        'Outside the apartment building doorway, bright day. Hayk (left, pose "give", face "smile") hands the red leash to Grant (FILM.cast.grant, right, pose "thumbsUp" after 1.5 s, face "confident"). Goofy sits between them looking up at Hayk, face "sad". Bubbles: Hayk at 0.5 s "GRANT, TAKE CARE OF GOOFY. ONE MONTH." Grant at 2.0 s "EASY. WHAT COULD GO WRONG?" with a sparkle on his teeth/glasses at 2.5 s. At 3.0 s Goofy turns to camera with a dark shadow over his eyes and a small "..." (foreshadowing). Leash drawn as a curve from Goofy\'s collar anchor to the hand anchor of whoever holds it.'),
      S('takeoff', '06-takeoff.js', 21, 26, 'Takeoff to Spain',
        'Zvartnots airport runway with Ararat behind at sunset (orange/pink sky). A white passenger plane (FILM.fx.plane) accelerates left to right with parallel speed lines and takes off on 22.0, then the camera whip-pans up (speed line wipe) at 23.5 to a stylised map of Europe: Armenia marked with a small flag at right, Spain at left; the plane icon flies along a dotted arc from Armenia to Spain between 24.0 and 25.5, with a caption bar "YEREVAN -> SPAIN" and "1 MONTH. MISSION: INVESTORS." Hayk\'s face visible in a plane window near the start, wearing sunglasses, grinning.'),

      // ACT 2: SPAIN (26-68)
      S('hola-espana', '07-hola-espana.js', 26, 30, 'Hola, Espana',
        'Bright Spanish street: warm sandstone buildings with balconies and flower pots, palm trees, a Sagrada-Familia-like spiky church silhouette in the distance, blue sky and a big sun with rays. Hayk walks in (pose "walk", sunglasses on, face "smile") pulling his suitcase, then strikes a pose ("peace") at 1.5 s with a sparkle burst. Big caption at 0.5 s: "DAY 1" and at 1.0 s a speech bubble "HOLA, ESPANA!" (write ESPANA as plain ASCII). At 2.5 s a to-do note card pops in the upper corner: "TODO: 1. FIND INVESTORS" with a checkbox.'),
      S('burger-scent', '08-burger-scent.js', 30, 34, 'The scent',
        'Same street, Hayk mid-walk. At 0.5 s a golden aroma ribbon (FILM.fx.aroma) curls in from off-screen right and reaches his nose. He freezes (face "shocked", sunglasses slide down his nose), dramatic black-and-white impact frame at 1.5 s (FILM.fx.impact) with his eyes wide. Extreme close-up on his eyes at 2.0 s with the reflection of a burger sign in his pupils and focus lines. Text at 2.5 s: "WAIT..." then at 3.0 s "IS THAT... A BURGER?!" in a shaky shout bubble. Katakana menace "ゴゴゴ" floating beside him.'),
      S('kfg', '09-kfg.js', 34, 39, 'KFG: bucket of chicken',
        'Parody fried-chicken restaurant "KFG" (red and white vertical stripes, a smiling old-colonel-like chicken logo that is clearly a cartoon CHICKEN with a bow tie, sign text "KFG" and small "KENTUCKY FRIED GOODNESS"). Hayk at a table, pose "eat", holding a drumstick (FILM.fx.drumstick), a big red-white bucket (FILM.fx.bucket label "KFG") in front of him. Each beat he takes a bite: big "CRUNCH!" SFX text on 35.0, 36.0, 37.0 with crumbs flying. Face "ecstatic" (anime food bliss: eyes closed happy arcs, glowing cheeks, sparkles). At 3.0 s golden light rays burst behind him. Caption top-left: "STOP 1: KFG".'),
      S('burger-kong', '10-burger-kong.js', 39, 44, 'Burger Kong',
        'Parody burger restaurant "BURGER KONG" (sign: burger bun shape with blue swoosh and a cartoon gorilla wearing a crown). Hayk wears a gold paper crown (FILM.fx.crown), holds a HUGE layered burger (FILM.fx.burger, s large) with both hands, pose "eatBig". At 1.0 s he unhinges his jaw anime-style and chomps: impact flash, "CHOMP!" SFX. At 2.0 s the burger is 1/3 gone (bite mask), at 3.0 s gone, and he raises a second burger. Bubble at 3.5 s: "ONE MORE. FOR RESEARCH." Caption top-left: "STOP 2: BURGER KONG".'),
      S('mcdonuts', '11-mcdonuts.js', 44, 49, 'McDonut\'s',
        'Parody restaurant "McDONUT\'S" (red facade, a big golden DONUT with a bite as the logo, not arches). Fries (FILM.fx.fries) rain from the sky in slow motion like a golden shower; Hayk catches them with his mouth open (pose "cheer", face "ecstatic"), sparkles everywhere. At 2.0 s he holds a tray with burger, fries, drink; at 3.0 s text "I\'M LOVIN\' IT" is NOT used; instead bubble: "BA DA BA BA BAAA!" (sung, with music notes). Caption top-left: "STOP 3: McDONUT\'S". His hoodie now looks slightly tighter (belly 0.25).'),
      S('food-nirvana', '12-food-nirvana.js', 49, 54, 'Burger nirvana',
        'Anime food-reaction climax (like a cooking anime): Hayk (pose "float", face "ecstatic", belly 0.35) floats in a cosmic space of purple and gold with stars and nebula swirls, burgers, fries and drumsticks orbiting him in an ellipse, his body glowing, hoodie fluttering. Golden light beams from behind. Big text at 1.0 s: "SO... GOOD...!!" (size ~110, gold with outline). At 2.5 s a halo of cheese drips. Radial focus lines pulse on every beat. At 4.0 s white flash out.', { transitionIn: { kind: 'flash', dur: 0.25, color: '#fff6d8' } }),
      S('day-counter', '13-day-counter.js', 54, 59, 'Days pass',
        'Montage of a tear-off calendar. Pages fly off on each bar (54.0, 56.0, 58.0) with whoosh speed lines. Each page shows "DAY 3", "DAY 12", "DAY 24" and under it a tally board: "INVESTORS MET: 0" and "BURGERS EATEN: 17" -> "58" -> "121" (numbers roll up). Beside the calendar, Hayk (pose "stand", face "happy" chewing) gets rounder each page: belly 0.4 -> 0.6 -> 0.8 using the cast belly parameter, holding a burger each time. A red "0" stamp slams on the INVESTORS line at 58.5 with a THUD.'),
      S('burger-chart', '14-burger-chart.js', 59, 64, 'Bullish on burgers',
        'Trading-terminal parody. Dark terminal background with grid. A candlestick chart where every candle is a tiny burger stack; the chart rockets up. Header: "BURGER/USD" and a label "ALL-TIME HIGH" flashing at 2.0 s. Hayk (pose "point", face "smug", belly 0.8, sunglasses) stands in front pointing at the chart like a teacher. Bubble at 1.5 s: "BULLISH ON BURGERS." Green arrow up with sparkle. At 3.5 s a tiny red candle labelled "INVESTORS" at the bottom, flat line.'),
      S('investor-call', '15-investor-call.js', 64, 68, 'An investor calls',
        'Close up: Hayk\'s hand and phone (FILM.fx.phone) buzzing with shake lines, screen shows "INVESTOR CALLING..." with a green and red button. Hayk\'s face (large, face "chewing", cheeks full like a hamster, belly irrelevant) in the upper part of the frame looks at it. At 1.5 s his thumb swipes red: "DECLINED" stamp. Bubble at 2.0 s (muffled): "MMF... LATER. BURGER FIRST." He takes another bite at 3.0 s, crumbs.'),

      // ACT 3: MEANWHILE IN YEREVAN (68-100)
      S('meanwhile', '16-meanwhile.js', 68, 71, 'Meanwhile in Yerevan',
        'Anime eyecatch-style card: diagonal split, half deep blue, half warm stripes; the Yerevan Cascade stairs and Ararat silhouette. Big text slams in at 0.5 s: "MEANWHILE..." then at 1.5 s "IN YEREVAN" (size ~90). A small cartoon of Goofy\'s head with an angry vein pops in the corner at 2.0 s.', { transitionIn: { kind: 'wipe', dur: 0.5, dir: 'right' } }),
      S('grant-walk', '17-grant-walk.js', 71, 75, 'Grant walks Goofy',
        'A calm Yerevan park with trees, benches and the Cascade stairs in the background, pastel morning light. Grant (pose "walk", face "calm", holding the leash) strolls left to right; Goofy (pose "walk") trots ahead on the leash. Grant whistles: music notes float from his mouth. Caption at 0.5 s: "DAY 1 OF DOG SITTING". Bubble at 2.0 s from Grant: "SEE? PEACEFUL." Parallax: background scrolls slower than the path.'),
      S('goofy-senses', '18-goofy-senses.js', 75, 79, 'Goofy senses a stranger',
        'Same park. Goofy stops dead. A stranger (a simple silhouette jogger with a small white poodle) appears on the right. Goofy\'s face switches to "angry" at 1.0 s: the frame darkens, red backlight, his eyes glow red, fur bristles, menacing katakana "ゴゴゴゴ" (FILM.fx.menace) rises around him, dark purple aura. Grant freezes behind with a sweat drop and face "nervous": bubble "UH-OH." at 2.5 s. Extreme close-up on Goofy\'s glowing eyes at 3.0 s.'),
      S('goofy-rampage', '19-goofy-rampage.js', 79, 84, 'WOOF WOOF WOOF',
        'Pure action. Goofy (pose "bark", face "angry", demon mode) barks aggressively on every beat 79.0 to 83.5: each bark is an impact with a giant "WOOF!" SFX text (alternating left/right, rotated, red and yellow with thick outline), shock rings from his mouth, screen shake. Grant (pose "pulled") is dragged horizontally like a flag in the wind behind the leash, face "panic", speed lines everywhere, leaves flying. At 2.5 s a black-and-white impact frame. The stranger runs away in the background.'),
      S('grant-calms', '20-grant-calms.js', 84, 89, 'Easy, Goofy...',
        'Grant (pose "kneel", face "calm" but sweating) kneels beside Goofy (pose "stand", face shifts from "angry" to "sad"). Soft calming palette: pale mint background with bubbles and gentle sparkles. Bubble at 0.5 s: "EASY, GOOFY... BREATHE..." Grant pats him; at 2.0 s bubble: "GOOD BOY. WHAT\'S WRONG?" Goofy\'s red eyes fade back to normal but his lip trembles, big tears build up in his eyes (face "sad") by 4.0 s.'),
      S('miss-hayk', '21-miss-hayk.js', 89, 95, 'I MISS HAYK',
        'The emotional peak, played for comedy. Goofy (pose "howl", face "cry") throws his head to the sky, waterfall anime tears gushing in two arcs forming puddles. The biggest text in the film: "I MISS HAAAAYK!!" in a huge jagged shout bubble at 1.0 s (letters shaking). Grant (face "shocked") falls backwards at 2.0 s with a "HE CAN TALK?!" small bubble at 3.0 s. Camera pulls back fast from 4.0 s: the park shrinks, then Yerevan, then a globe with Armenia and Spain, and the howl text echoes smaller.'),
      S('video-call', '22-video-call.js', 95, 100, 'Video call',
        'Split screen, vertical: top half Spain (Hayk in a restaurant, belly 0.8, face "chewing", burger in mouth, crown on head), bottom half Yerevan (Grant holding the phone out, Goofy face "cry" pressed against the screen). A phone-UI frame around each half ("VIDEO CALL 00:07"). At 1.0 s bubble from Goofy: "HAYK... COME BACK..." At 2.5 s Hayk\'s eyes go wide, face "shocked", bubble "GOOFY?!". At 3.5 s the burger starts to drop from his mouth.'),

      // ACT 4: HOMECOMING (100-120)
      S('burger-drop', '23-burger-drop.js', 100, 104, 'The burger falls',
        'Slow motion. The half-eaten burger falls in close up past Hayk, tumbling, sesame seeds floating, dramatic blue-white focus lines, time-freeze effect with film-frame lines. Hayk (face "determined", eyes with sparkle, pose "fist") in the background as the burger hits the table on 102.0 with an impact frame. He stands, hoodie billows, fire aura. Shout bubble at 2.5 s: "I\'M COMING HOME, GOOFY!"'),
      S('fly-home', '24-fly-home.js', 104, 108, 'Flying home',
        'The map from shot 06 again but reversed: the plane flies Spain -> Armenia along the dotted arc, much faster, with fire trails and speed lines. The plane looks slightly heavier/lower (a burger-shaped bag hanging out of the cargo door as a gag). Caption: "SPAIN -> YEREVAN" and "MISSION: GOOFY". At 2.5 s the plane lands with a big dust cloud and "SKRRT!" SFX.', { transitionIn: { kind: 'wipe', dur: 0.5, dir: 'left' } }),
      S('reunion', '25-reunion.js', 108, 114, 'The reunion',
        'Classic anime slow-motion reunion run in a field of flowers at golden hour, pink and gold bokeh, petals flying. Hayk (pose "run", face "cry" happy tears, belly 0.8) runs from the left, Goofy (pose "run", face "happy", tongue out) from the right. At 2.0 s they meet in the middle: flash, Goofy leaps (pose "jump") into Hayk\'s arms (Hayk pose "hug"), hearts burst. Grant in the background (pose "collapse", face "exhausted") lying flat on the ground with a speech bubble "FINALLY..." at 4.0 s.'),
      S('the-end', '26-the-end.js', 114, 120, 'The end',
        'Final group shot in front of Ararat at sunset: Hayk (pose "stand", belly 0.8, face "happy", crown) holding Goofy, Goofy (face "happy") happily eating a burger, Grant (face "exhausted") giving a thumbs up with bandages on his arm. Stats card slides in at 1.0 s, one line per beat: "INVESTORS FOUND: 0", "BURGERS EATEN: 147", "KILOS GAINED: 9", "GOOFY: HAPPY" (each with a tick). At 3.5 s "THE END?" in big gold letters, with small "LIQUIDITYSCAN" logo under it. Last 0.5 s holds.'),
    ],

    cues: [
      { t: 0, kind: 'hit', note: 'Taiko boom + reverse cymbal into the title' },
      { t: 0.5, kind: 'hit', note: 'Focus-line explosion: impact whoosh' },
      { t: 1, kind: 'hit', note: 'Title slam: big drum hit, brass stab, crash' },
      { t: 2, kind: 'sfx', note: 'Burger sparkle chime' },
      { t: 4, kind: 'cut', note: 'Lo-fi trader beat starts: soft kick, hats, keys' },
      { t: 5, kind: 'sfx', note: 'Intro card whoosh' },
      { t: 7, kind: 'sfx', note: 'PING: candle spike chime' },
      { t: 9, kind: 'hit', note: 'Chair spin whoosh + impact, epic drums enter' },
      { t: 9.5, kind: 'hit', note: 'Shout impact' },
      { t: 11, kind: 'hit', note: 'Second shout impact' },
      { t: 13, kind: 'cut', note: 'Music drops to a sad piano; a small whine' },
      { t: 16, kind: 'sfx', note: 'Footsteps' },
      { t: 17, kind: 'cut', note: 'Light comedic bounce returns' },
      { t: 19.5, kind: 'sfx', note: 'Teeth sparkle ting' },
      { t: 20, kind: 'sfx', note: 'Ominous low note for Goofy' },
      { t: 21, kind: 'cut', note: 'Jet engine rising' },
      { t: 22, kind: 'hit', note: 'Takeoff whoosh' },
      { t: 23.5, kind: 'sfx', note: 'Whip-pan swish' },
      { t: 26, kind: 'cut', note: 'Spanish guitar flamenco groove starts' },
      { t: 27.5, kind: 'sfx', note: 'Pose sparkle' },
      { t: 30, kind: 'cut', note: 'Groove continues' },
      { t: 31.5, kind: 'hit', note: 'Impact frame: dramatic sting' },
      { t: 33, kind: 'hit', note: 'Shout sting' },
      { t: 34, kind: 'cut', note: 'Eating montage beat starts, heavy and funky' },
      { t: 35, kind: 'sfx', note: 'CRUNCH' },
      { t: 36, kind: 'sfx', note: 'CRUNCH' },
      { t: 37, kind: 'sfx', note: 'CRUNCH' },
      { t: 40, kind: 'hit', note: 'CHOMP impact' },
      { t: 44, kind: 'cut', note: 'Stop 3' },
      { t: 49, kind: 'hit', note: 'Choir swell for food nirvana' },
      { t: 54, kind: 'sfx', note: 'Page whoosh' },
      { t: 56, kind: 'sfx', note: 'Page whoosh' },
      { t: 58, kind: 'sfx', note: 'Page whoosh' },
      { t: 58.5, kind: 'hit', note: 'Stamp THUD' },
      { t: 59, kind: 'cut', note: 'Synthy trader beat' },
      { t: 64, kind: 'sfx', note: 'Phone buzz' },
      { t: 65.5, kind: 'hit', note: 'Decline swipe' },
      { t: 68, kind: 'hit', note: 'Eyecatch sting' },
      { t: 71, kind: 'cut', note: 'Calm whistle theme, acoustic' },
      { t: 75, kind: 'cut', note: 'Music stops; suspense drone' },
      { t: 76, kind: 'hit', note: 'Menace rumble' },
      { t: 79, kind: 'hit', note: 'Bark 1, battle drums' },
      { t: 79.5, kind: 'sfx', note: 'Bark' },
      { t: 80, kind: 'sfx', note: 'Bark' },
      { t: 80.5, kind: 'sfx', note: 'Bark' },
      { t: 81, kind: 'sfx', note: 'Bark' },
      { t: 81.5, kind: 'hit', note: 'Impact frame bark' },
      { t: 82, kind: 'sfx', note: 'Bark' },
      { t: 82.5, kind: 'sfx', note: 'Bark' },
      { t: 83, kind: 'sfx', note: 'Bark' },
      { t: 83.5, kind: 'sfx', note: 'Bark' },
      { t: 84, kind: 'cut', note: 'Calm harp and pads' },
      { t: 89, kind: 'hit', note: 'Sad epic strings + howl' },
      { t: 90, kind: 'hit', note: 'I MISS HAYK: big howl' },
      { t: 93, kind: 'sfx', note: 'Zoom-out whoosh' },
      { t: 95, kind: 'cut', note: 'Video call ring' },
      { t: 97.5, kind: 'hit', note: 'Shock sting' },
      { t: 100, kind: 'cut', note: 'Slow-motion heartbeat' },
      { t: 102, kind: 'hit', note: 'Burger impact' },
      { t: 104, kind: 'hit', note: 'Heroic brass theme' },
      { t: 106.5, kind: 'hit', note: 'Landing SKRRT' },
      { t: 108, kind: 'cut', note: 'Emotional reunion theme' },
      { t: 110, kind: 'hit', note: 'Reunion hug flash' },
      { t: 114, kind: 'cut', note: 'Ending theme, happy' },
      { t: 117.5, kind: 'hit', note: 'THE END? stinger' },
    ],
  };
})();
